### ISSUE TITLE
Red Moon disables touch events in ownCloid app

### ISSUE THREAD

**Issue by dbolton** [raatmarien/red-moon#108]
Steps to reproduce
1. Open and activate Red Moon
2. Open the ownCloud app
3. Tap to open a folder or file

Expected behavior
ownCloud should respond by opening the file or folder

Actual behavior
ownCloud doesn't respond to touch

**Comment by smichel17** [comment]
Owncloud has marked their app as secure, which prevents you from interacting with it if there is another app overlaid on top of it (so no other app can watch your touches and figure out what you're doing, or mislead you into clicking something you didn't mean to).

Red Moon uses an overlay to display the filter, so unfortunately Owncloud will not work when Red Moon is enabled. Nothing short of making Red Moon a root app will fix this (see #20).

The workaround is to pause Red Moon when opening Owncloud. If you're running Red Moon v2.9.2 (the latest release), this should happen automatically if you enable the `Automatically suspend filter in secure apps` setting.

**Comment by dbolton** [comment]
Makes sense. Thank you for the explanation.
