### ISSUE TITLE
Tasker integration

### ISSUE THREAD

**Issue by cycojesus** [raatmarien/red-moon#11]
Allow control with a plugin for Tasker as documented @ http://tasker.dinglisch.net/plugins.html

**Comment by raatmarien** [comment]
Thanks for the suggestion!

I'm not going to implement Tasker at this time, as I'd rather not force the end user to use an propietary app for scheduling. I'd rather implement a separate time scheduling feature in the app itself (see #5).

However, if it's possible to support Tasker without including any proprietary code or libraries, then I'd accept any pull requests, if anyone feels like implementing it.

**Comment by dim-geo** [comment]
There are also two alternatives which should be enough for beginning:
shortcuts
intents

Using one of them will allow tasker integration

**Comment by raatmarien** [comment]
I've added a shortcut to toggle the filter, this will allow users to integrate Red Moon with Tasker.

**Comment by smichel17** [comment]
See also #80.
