### ISSUE TITLE
Package installer not recognized as secure app

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#110]
- On my Samsung Galaxy s6, api 23, Red Moon does not recognize the package installer as a secure app.
- App monitoring is working, though, because it pauses in owncloud.
- It does recognize the package installer on an emulated api 23 device.

I presume that Samsung is shipping a modified package installer with a different package name. But I don't have time to do the research to figure out what it is.

If someone can find out if my hunch is correct and if so, what the package name is, I can fix this bug very easily.

**Comment by raatmarien** [comment]
To find out what the package name of the installer on Samsung is, you can try the following. 

1. Enable DEBUG for CurrentAppMonitoringThread. 
2. Turn on Red Moon's filter with suspend in secure apps
3. Monitor the logcat for the debug statement from this line https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/thread/CurrentAppMonitoringThread.kt#L47 to find out what the packagename of the installer is.

You can then add this to the list of secure package names. Could you try this when you find the time @smichel17? I don't have any Samsung devices to test it on.

**Comment by smichel17** [comment]
Right, that makes sense. Can do tomorrow I think.
