### ISSUE TITLE
loading screen is bright white

### ISSUE THREAD

**Issue by kilroythe5th** [raatmarien/red-moon#112]
it would be cool if red moon showed a black or dark initial loading screen, since it's usually being used in the night

**Comment by cao-** [comment]
What about using the dark theme?

**Comment by smichel17** [comment]
@cao- I believe @kilroythe5th is referring to the [placeholder ui](https://material.io/guidelines/patterns/launch-screens.html#launch-screens-placeholder-ui) shown between clicking the app's button and when the app actually loads, which does have a white background.

Red Moon loads pretty quickly, so you might not even see this screen on a new device.

The issue with choosing either white or the dark theme grey background is that it looks bad to flash white before grey, and it also looks bad to flash grey before white. Probably red is the best solution.
