### ISSUE TITLE
When are you going to update the Google Play version?

### ISSUE THREAD

**Issue by NoahAndrews** [raatmarien/red-moon#127]

**Comment by smichel17** [comment]
I can't answer the question since I'm not @raatmarien, but as a workaround, you should be able to upgrade by installing the apk on github's [releases](https://github.com/raatmarien/red-moon/releases) page.

**Comment by raatmarien** [comment]
Sorry it took a while, I've published v2.10.0 on Google Play. It should be available in a few hours.
