### ISSUE TITLE
Automatic dimming doesn't work in 2.10.0

### ISSUE THREAD

**Issue by StefanBrand** [raatmarien/red-moon#128]
Hi, I had to roll back to 2.9.2 because in 2.10.0 Red Moon didn't turn off the filter in the morning. (I am not sure, if it also doesn't automatically turn on in the evening.)

Red Moon finds the location and it seems as if it would apply the correct sunrise time in the greyed out field. It simply doesn't turn off the filter at that time.

PS: Using a Fairphone 1 on KitKat 4.4.2.

**Comment by smichel17** [comment]
Fixed in 2.10.1. There is a workaround in 2.10.0. See #126.

**Comment by smichel17** [comment]
Let's leave this open until 2.10.1 comes out on gplay and f-droid so other people who might come here see it.
