### ISSUE TITLE
Pause button disappears from the dropdown notification

### ISSUE THREAD

**Issue by rplevka** [raatmarien/red-moon#129]
I don't know, whether this is a bug or a toggleable feature, but I usually loose the pause/continue button + profile switch from the dropdown notification area notif.
i need to enter redmoon ui in order to pause/unpause, ehich gets annoying.
Restarting the app did not bring the buttons back. Any ideas?

**Comment by smichel17** [comment]
Android will sometimes collapse notifications and hide their actions. You can expand them again by tapping on them and dragging down. If that's what's going on, this is just how Android works and there's nothing we can change about it. If it's something else, sounds like a bug. Is it also missing the action to switch profiles?

**Comment by rplevka** [comment]
@smichel17 ha! you're right, i've been a long-time user yet android can still surprise me :)

thanks again
