### ISSUE TITLE
Respect daylight saving time with location based filter times

### ISSUE THREAD

**Issue by katsel** [raatmarien/red-moon#134]
I have "Filter times" set to "Times from location", to adjust color temperature based on sunrise/sunset. Worked perfectly so far, I'm really enjoying that feature of Red Moon.

We went to daylight saving time last night. Android adjusts time settings of my device automatically when that happens. However, Red Moon did not adapt to that change and switched to night mode 1 hour too early.

I would suggest to make Red Moon aware of daylight saving time if "Times from location" is enabled.

Side note: I just rebooted my phone to see if this helps with the issue, and I can report back if it worked (in case that's interesting). Still, if it's possible to have a fix that doesn't require reboot, that'd be more user friendly.

I'm using version 2.10.1.

**Comment by smichel17** [comment]
Red moon should use the phone's time to schedule,  and each event is scheduled when the previous one happens. So, I suspect that it will correct itself after a cycle or two.

You can also force the times to reschedule by turning the timer off and on again.

**Comment by katsel** [comment]
@smichel17: I tried your suggestion, but I still showing got incorrect sunrise/sunset times.

I got it working as follows:
1. enable GPS
2. switch "Times from location" off and on again.

This corrected the times.

I noticed that it's not just a daylight saving time issue. Once you enable "Times from location", Red Moon seems to stick with sunrise/sunset times from that single day. The thing is, sunrise/sunset times change _every single day_ by a few minutes. After just a few weeks, Red Moon is off by half an hour or more.

**Comment by smichel17** [comment]
I think I know the issue and a fix.

**Comment by smichel17** [comment]
Agreed. There's some improvement to that in v2.10.2 but not a full fix. I'll do the full fix in v3.0.1.

**Comment by katsel** [comment]
Sounds good to me. Thanks for taking care of this!
