### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by doronbehar** [raatmarien/red-moon#145]
Hello dear red moon developers,

this is not a real issue, I just wanted to point out how satisfied I am since the last update. The way users can create, delete and restore filters themselves and so on is just fantastic. I'm so happy the free software movement has brilliant developers like you on our side.

Thank you so much for creating this app for us, God bless you, God bless free software.

**Comment by smichel17** [comment]
Thank you for the kind words! I'm going to close this just to keep the issues section clean :)
