### ISSUE TITLE
don't redden black pixels (subtractive filter)

### ISSUE THREAD

**Issue by travisfw** [raatmarien/red-moon#149]
I notice that the black area around my ◁○□ (triangle, circle, square) buttons turns red with Red Moon on. I haven't been using Red Moon because it seemed to make everything look muddy, and this explains it. You're fading the whole screen towards red. As internet cats would say, ur doin it wrong. Ideally you should be applying a subtractive filter, like looking through red cellophane. Nothing that didn't already have red in it should look at all red. Pure blue and pure green, no matter the shade, and every mix of those two colors without red, should fade towards black to the degree of the "intensity level" of a red color temp, but should never appear at all red. I don't know how the app, or Android, works, but subtractive filtering is common in graphics and should be available, IE, I would be surprised if you have to write this or are otherwise unable to do it.

**Comment by smichel17** [comment]
This requires root. Discussed quite a bit more in #20.
