### ISSUE TITLE
Add Shortcut to activate/deactivate

### ISSUE THREAD

**Issue by dim-geo** [raatmarien/red-moon#16]
Hi,

Please add shortcut to activate /deactivate.
By enabling this tasker is intergrated via autoshortcut application.
Also, it will allow users to have a widget to turn on/off.

**Comment by raatmarien** [comment]
Hey, thanks for the suggestion!

A widget is available in v2.4.0+ which will be up on f-droid shortly (should be about a day).

Is a widget enough for tasker support or do you need a shortcut specifically? If so, what exactly do you mean with a shortcut? I can't seem to find much information on the subject.

**Comment by dim-geo** [comment]
Widget is not enough.
You are right, documentation about shortcuts seems scarce.
Shortcut is different from a widget. When you add a quick dial for a contact you actually add a shortcut, not a widget. I found this:
http://www.kind-kristiansen.no/2010/android-adding-desktop-shortcut-support-to-your-app/

Another idea for tasker support is intent. Does your app has an intent to toggle filter?
If you have then, it's easy to call this intent through tasker.

**Comment by raatmarien** [comment]
Thanks for the link!

I've followed the instructions on that site and the I've added an shortcut to toggle the filter.

This feature will probably be present in the next version of Red Moon
