### ISSUE TITLE
Google Play Purchasing Issue

### ISSUE THREAD

**Issue by adisib** [raatmarien/red-moon#163]
I have used the github version of your app and found it to be quite nice (other than that it seems to randomly turn off every so often; perhaps a crash?). I decided to purchase your app to get automatic updates and show my support as a result, and so first uninstalled the github version.

Unfortunately, I am unable to purchase your app from the Google Play Store. After several weeks of fighting against Google's terrible support, they have told me that it is your issue and said I should talk to you (though I would think they should be informing you of the issue, not delegating it to a random user). They said that developers are responsible for delivering the app. The Play Store gave me no other information than that the transaction was declined, and the support conversations with Google have not given me any more information.

I highly recommend you investigate the purchasing issue so people can properly compensate you for your app. Google support doesn't really seem to know what they are talking about, so I wish you luck on making some progress if you need to contact them. If you do get this resolved, please let me know so that I can finally purchase your app and not have to wait another month.

I also have not seem much github activity, so please respond to this issue as soon as you can so I know that I don't have to look for an alternative method of contacting you.

**Comment by smichel17** [comment]
> quite nice

Thank you :)

> (other than that it seems to randomly turn off every so often; perhaps a crash?)

Feel free to open an issue and I'll see if we can figure out the cause.

> to get automatic updates

Note, you can also do this [through f-droid](https://f-droid.org/packages/com.jmstudios.redmoon/).

> Unfortunately, I am unable to purchase your app from the Google Play Store. 

Is it the same issue as #148?

> I also have not seem much github activity, so please respond to this issue as soon as you can so I know that I don't have to look for an alternative method of contacting you.

@raatmarien is the one publishing it, so I can't help you very much here. He hasn't been around very much this summer, so I'm not sure when you can expect a response. You can find his email address on the 'about' screen in Red Moon.
