### ISSUE TITLE
Update for project!!

### ISSUE THREAD

**Issue by MrYKaushiK** [raatmarien/red-moon#164]
Hello,

Thank You for this Awesome app!!!

but please tell me:- How to update this project in Android Studio????

**Comment by smichel17** [comment]
Assuming you downloaded the code using git and didn't change any of the default git settings, running, `git pull origin master` in a terminal from inside the directory with the code will do it.

Android studio has a git plugin (might be called VCS - version control system) that can do the same thing. I prefer running the git commands manually so I have more control, so I don't use the plugin and don't know how to use it off hand. I'm sure you can find info Googling/Ducking it.

**Comment by smichel17** [comment]
Closing this since it's not specific to Red Moon.
