### ISSUE TITLE
Add a scheduler

### ISSUE THREAD

**Issue by jvoisin** [raatmarien/red-moon#17]
It would be great if redmoon could be (de)activated automatically at certain hours.

**Comment by raatmarien** [comment]
Hey, thanks for the feedback! 

I'm actually currently working on this feature. I plan to have it incorporated into the next release.

**Comment by jvoisin** [comment]
Wonderful ♥

**Comment by raatmarien** [comment]
One can now choose times at which to automatically turn on or turn off the filter. The new release with this feature should be on F-Droid in a few days.
