### ISSUE TITLE
Force close on start

### ISSUE THREAD

**Issue by Locash** [raatmarien/red-moon#173]
Hello. 
       I am having an issue on ver.3.1 and ver.3.0. With an error and force close.
It does NOT happen with ver. 2.10.2😀 So I'm using that version.
Lg 410 stock 4.4.2 rooted exposed

09-06 03:09:39.046: D/WallpaperManager(1497):  suggestDesiredDimensions(800, 1280) by package(com.lge.launcher2)
09-06 03:09:41.436: I/ActivityManager(1497):  Timeline: Activity_launch_request id:com.jmstudios.redmoon time:884851
09-06 03:09:41.436: I/ActivityManager(1124):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.jmstudios.redmoon/.ui.MainActivity} from pid 1497
09-06 03:09:41.436: I/ActivityManager(1124):  ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t-1} Support Split:false Is ScreenFull:true
09-06 03:09:41.536: D/ActivityManager(1124):  resumeTopActivityLocked: Restarting ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14}
09-06 03:09:41.546: I/ActivityManager(1124):  Start proc com.jmstudios.redmoon for activity com.jmstudios.redmoon/.ui.MainActivity: pid=9627 uid=10286 gids={50286}
09-06 03:09:41.566: V/ActivityManager(1124):  Moving to RESUMED: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14} (starting new instance)
09-06 03:09:41.576: I/SystemUI[Framework](1124):  PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x0, pkg=com.jmstudios.redmoon
09-06 03:09:41.696: I/dalvikvm(9627):  Failed resolving Lcom/jmstudios/redmoon/model/ProfilesModel$restoreDefaultProfiles$1; interface 3032 'Ljava/util/function/BiConsumer;'
09-06 03:09:41.696: W/dalvikvm(9627):  Link of class 'Lcom/jmstudios/redmoon/model/ProfilesModel$restoreDefaultProfiles$1;' failed
09-06 03:09:41.696: E/dalvikvm(9627):  Could not find class 'com.jmstudios.redmoon.model.ProfilesModel$restoreDefaultProfiles$1', referenced from method com.jmstudios.redmoon.model.ProfilesModel.restoreDefaultProfiles
09-06 03:09:41.696: W/dalvikvm(9627):  VFY: unable to resolve new-instance 2749 (Lcom/jmstudios/redmoon/model/ProfilesModel$restoreDefaultProfiles$1;) in Lcom/jmstudios/redmoon/model/ProfilesModel;
09-06 03:09:41.696: I/dalvikvm(9627):  Failed resolving Lcom/jmstudios/redmoon/model/ProfilesModel$restoreDefaultProfiles$1; interface 3032 'Ljava/util/function/BiConsumer;'
09-06 03:09:41.696: W/dalvikvm(9627):  Link of class 'Lcom/jmstudios/redmoon/model/ProfilesModel$restoreDefaultProfiles$1;' failed
09-06 03:09:41.696: D/dalvikvm(9627):  DexOpt: unable to opt direct call 0x589e at 0x0e in Lcom/jmstudios/redmoon/model/ProfilesModel;.restoreDefaultProfiles
09-06 03:09:41.696: E/AndroidRuntime(9627):  Process: com.jmstudios.redmoon, PID: 9627
09-06 03:09:41.696: E/AndroidRuntime(9627):  java.lang.NoClassDefFoundError: com.jmstudios.redmoon.model.ProfilesModel$restoreDefaultProfiles$1
09-06 03:09:41.696: E/AndroidRuntime(9627):  	at com.jmstudios.redmoon.model.ProfilesModel.restoreDefaultProfiles(ProfilesModel.kt:78)
09-06 03:09:41.696: E/AndroidRuntime(9627):  	at com.jmstudios.redmoon.RedMoonApplication.upgradeProfilesFrom(RedMoonApplication.kt:89)
09-06 03:09:41.696: E/AndroidRuntime(9627):  	at com.jmstudios.redmoon.RedMoonApplication.upgradeFrom(RedMoonApplication.kt:43)
09-06 03:09:41.696: E/AndroidRuntime(9627):  	at com.jmstudios.redmoon.RedMoonApplication.onCreate(RedMoonApplication.kt:27)
09-06 03:09:41.706: W/ActivityManager(1124):    Force finishing activity com.jmstudios.redmoon/.ui.MainActivity
09-06 03:09:41.706: V/ActivityManager(1124):  Moving to PAUSING: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f}
09-06 03:09:42.006: I/WindowManager(1124):  Screenshot max retries 4 of Token{42d77000 ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f}} appWin=Window{4240eb00 u0 Starting com.jmstudios.redmoon} drawState=4
09-06 03:09:42.506: W/ActivityManager(1124):  Activity pause timeout for ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f}
09-06 03:09:42.506: V/ActivityManager(1124):  Moving to PAUSED: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f} (due to timeout)
09-06 03:09:42.506: V/ActivityManager(1124):  Moving to FINISHING: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f}
09-06 03:09:42.516: D/ActivityManager(1124):  allPausedActivitiesComplete: r=ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f} state=FINISHING
09-06 03:09:42.526: D/WallpaperManager(1497):  suggestDesiredDimensions(800, 1280) by package(com.lge.launcher2)
09-06 03:09:42.626: V/ActivityManager(1124):  Moving to DESTROYING: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f} (destroy requested)
09-06 03:09:43.516: I/ActivityManager(1124):  Process com.jmstudios.redmoon (pid 9627) has died.
09-06 03:09:43.516: V/ActivityManager(1124):  Moving to DESTROYED: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f} (removed from history)
09-06 03:09:43.516: V/ActivityManager(1124):  Moving to DESTROYED: ActivityRecord{4337f810 u0 com.jmstudios.redmoon/.ui.MainActivity t14 f} (cleaning up)

[2017-09-06-03_10_05.txt](https://github.com/raatmarien/red-moon/files/1280305/2017-09-06-03_10_05.txt)

**Comment by smichel17** [comment]
Fixed in v3.1.1, see #171 :)

I'll leave this open until the fix shows up on f-droid, so other people don't miss it.

**Comment by Asara** [comment]
Just noticed this last night myself.  Downgraded to the previous version.  Will wait for an update.

Thanks!

**Comment by smichel17** [comment]
F-droid builds based on git tags, and I tagged v3.1.1 yesterday, so it should catch the update today.

**Comment by smichel17** [comment]
Turns out I broke F-Droid automatic builds in 3.1.0, too 📦 
Fixed that now, too, so this should be out shortly.
