### ISSUE TITLE
Restore default filters not working

### ISSUE THREAD

**Issue by Bubu** [raatmarien/red-moon#175]
First thing I did after installing the app was of course to mess with all the settings. Now I wanted to restore the default color temperature and intensity settings and there is apparently an option that restores the default filters. 

But after clicking that I still have only one custom filter which is not at default settings.

**Comment by smichel17** [comment]
Can you check if adding and removing profiles works, and whether changes are applied after closing the app, swiping it away from the recent apps, and opening it again?

If so, this was fixed in c4d8723 and will be in the next release.

**Comment by Bubu** [comment]
The default profiles are indeed there after reopening the app. Also saving profiles only works when closing the app and opening again. So this seems to be the problem you described?

**Comment by smichel17** [comment]
Yes, it was a problem with caching. It's fixed and released and should appear on F-Droid the next time they update.

**Comment by Bubu** [comment]
Cool, let's close this then :)
