### ISSUE TITLE
Notification tile not working

### ISSUE THREAD

**Issue by mueller-ma** [raatmarien/red-moon#176]
Nothing happens when I tab on the notification tile.
Android 7.1.2
Lineageos 14.1

**Comment by smichel17** [comment]
Beat you by a few days: 15f6811 :P

**Comment by smichel17** [comment]
Actually, I'll leave this open until it does come out on f-droid, so others don't miss it.

**Comment by mueller-ma** [comment]
This will toggle the filter?

**Comment by smichel17** [comment]
Yeah. There's a helper function to toggle the filter, and I just accidentally swapped on and off while I was refactoring that code (root mode prep). So when the filter is on, tapping the tile currently tries to turn it on again, and the same for when it's off. That commit just swaps it back the way it should be.

**Comment by mueller-ma** [comment]
Because of this tile it might be a good idea to disable the notification

**Comment by smichel17** [comment]
The notification is needed for Android memory management, to keep Android from killing the service unless the phone has so little memory that there's no choice. On android 8.0 there is a smaller notification, that we will switch to, if we decide to support 8.0 (#169).
