### ISSUE TITLE
V 3.1.0: application stopped

### ISSUE THREAD

**Issue by hjbeckers** [raatmarien/red-moon#178]
When I try to start above version on a Samsung Galaxy Note 4 (Android version 6.0.1, security patches as of 17-08-01), I get a message "red moon stopped/halted ". The previous version 3.0.0 works without problems. Does the new version need new rights? 

Hint: The Samsung "s-planner" app has the same problem when I try to send a calendar entry from another application.

**Comment by smichel17** [comment]
This is a bug, duplicate of #171 and #173. Fixed 5 days ago but F-Droid hasn't published the new version yet :(
