### ISSUE TITLE
[F-Droid] 3.1.2 Still Crashes On Marshmallow 

### ISSUE THREAD

**Issue by BrainBlasted** [raatmarien/red-moon#183]
**Device** : ZTE Zmax Pro

**Android Version** : 6.0.1

I've had this issue for a while, and the latest releases haven't fixed it. What can I do to help fix this?

**Comment by BrainBlasted** [comment]
Closing after seeing issue #180

**Comment by smichel17** [comment]
Since the crash is only on upgrade, as a workaround you can clear all data, or uninstall/reinstall.
