### ISSUE TITLE
Crashes when turned on on CM13

### ISSUE THREAD

**Issue by ujinv** [raatmarien/red-moon#2]
On android 6.0.1 (cm13) ui shows ok, when i push enable button error appears: app stopped working. Then notification tray is trying to load smthng and the same error is shown again.

**Comment by raatmarien** [comment]
Thanks for letting me know, I'll look into it.

**Comment by raatmarien** [comment]
Turns out the app wasn't properly requesting permissions for Android 6.0 and above, since drawing over other apps is considered a dangerous permission. I fixed it now, thanks for letting me know about the issue.
