### ISSUE TITLE
Red Moon doesn't work on Xperia Z3c

### ISSUE THREAD

**Issue by bungabunga** [raatmarien/red-moon#22]
I tried to run Red Moon on my device but nothing happens when i enable the filter, even at night.

Is there anything i can do to help you solve this issue?

Sony Xperia Z3c
Android 5.1

**Comment by raatmarien** [comment]
Thanks for letting me know!

Could you tell me a few things, to help me find the cause?
* What version of Red Moon are you running?
* Are you running stock android or a custom ROM?
* If you press the switch, does the switch flip or does it stay off?
* Do you have the setting "Automatically turn on filter" set to "Never"?
* If you turn on the filter, do you get a notification in your notification tray from Red Moon?

**Comment by bungabunga** [comment]
Hey,

- I'm running Red Moon 2.6.2
- I'm running a rooted stock ROM (commercial Twighlight app is working without problems)
- Yes, the switch flips, but nothing happens
- I tried all possibilities, but, yes, when switching filter on with "Never" set nothing happens.
- I get a **"Red Moon - Running. Pause to install apks"** box with buttons to pause, stop or go to settings.

**Comment by raatmarien** [comment]
Thanks for the information!

I don't know what is causing this, but I'll look into it.

Sorry for the inconvenience.

**Comment by smichel17** [comment]
@raatmarien Are there any logs that @bungabunga could provide to help you diagnose the issue?

If so, is it worth adding in a 'debug log' setting to facilitate producing those?

**Comment by bungabunga** [comment]
is it still possible to get a usable debug log on Android 5.1 with Catlog app?

**Comment by raatmarien** [comment]
I think it is still possible to get the logs with the Catlog app, so if you would be able to do that, it would be very helpful.

Could you also try one more thing for me? Could you try turning the intensity and the dim slider all the way up to the maximum, to see if that changes anything?

Thanks in advance.

**Comment by bungabunga** [comment]
i tried that and nothing happens.

will get a logcat.

**Comment by raatmarien** [comment]
Okay, thanks!

**Comment by bungabunga** [comment]
hey, just forget about it all!

i just realised that i forgot to switch off Xprivacy restrictions from Red Moon so nothing strange that it didn't work.

and i want to appologise to you guys for taking your precious time not being careful enough. sorry. :/

you made a great app and I'm happy to replace a non-opensource app with Red Moon.

**Comment by raatmarien** [comment]
No problem at all, glad it works again!
