### ISSUE TITLE
How to translate to lithuanian language

### ISSUE THREAD

**Issue by techwebpd** [raatmarien/red-moon#23]
great app, how to translate it to lithuanian lang, can i create values-lt folder and put in it strings file. Where are the english strings file to use it as a template?

**Comment by raatmarien** [comment]
To translate Red Moon to Lithuanian, you can indeed create a new strings.xml file in a values-lt directory. You can find the English strings file [here](https://github.com/raatmarien/red-moon/blob/master/app/src/main/res/values/strings.xml). To create the Lithuanian translation, just copy the [standard strings.xml file](https://github.com/raatmarien/red-moon/blob/master/app/src/main/res/values/strings.xml), remove any strings with the 'translatable="false"'-tag and translate the English strings between the <string> tags to Lithuanian.

If you have any further questions, don't hesitate to ask.

**Comment by techwebpd** [comment]
i translated and pulled

**Comment by raatmarien** [comment]
Great, thanks!
