### ISSUE TITLE
move to GPL

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#26]
I was wondering how you'd feel about moving to GPLv3+.

I love that there's now a usable free software replacement to proprietary screen filter apps, and I'd like to work to make it better than those -- but I'd also be sad if a proprietary fork with added features came along and this app died out because they didn't give back.

To be 100% clear, that is NOT a threat. I have already done 85% of a UX overhaul for this app, which I will post in a mega-issue soon, no matter which license you decide to go with. the spirit of [FLO](https://snowdrift.coop/p/snowdrift/w/en/free-libre-open) development is collaboration; I do not want this to become a divisive, mud-slinging argument. I do have a preference and I hope you will consider switching. :)

**Comment by raatmarien** [comment]
Hey, thanks for the suggestion!

I actually prefer the GPL too, the reason that I've licensed Red Moon under the MIT License for now is that [Shades](https://github.com/cngu/shades), which Red Moon is based on, was already MIT and I'm not sure how to relicense it.

Do you know how I would go about relicensing to the GPLv3+?

**Comment by smichel17** [comment]
I've done CC-BY -> CC-BY-SA before, but never I've never done MIT -> GPL. I know that (1) the law is not super clear about this stuff and different lawyers have different interpretations of what's acceptable, and (2) there are some differences between CC licenses (particularly moving between them) and software licenses. That said, in the fork I did, I included the following in my README.md, names and licenses changed to reflect this project:

>[Red Moon](https://github.com/raatmarien/red-moon/) is a derivative of [Shades](https://github.com/cngu/shades) by [Chris Nguyen](https://github.com/cngu), used under the [MIT License](https://opensource.org/licenses/MIT). [Red Moon](https://github.com/raatmarien/red-moon/) is licensed under the [GPL version 3](https://www.gnu.org/licenses/gpl-3.0.html) or later by [Marien Raat](https://github.com/raatmarien).

Someone more knowledgeable than me just pointed out [this article](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html).

If @cngu @twckr @Zoraver @stragu @techwebpd and @danialbehzadi are willing to license their code under the GPLv3+, it is less work to switch. If they don't you'll just need to include notices in various places about some of the code being licensed under the MIT license. They can give that permission by commenting on this thread with "I give permission to use my contributions under the GPLv3 or (at your option) any later version."

**Comment by twckr** [comment]
That's all right with me.

**Comment by stragu** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I give permission to use my contributions under the GPLv3 or (at your option) any later version.

Cheers raatmarien.

On April 3, 2016 5:11:42 AM AEST, smichel17 <notifications@github.com> wrote:
>I've done CC-BY -> CC-BY-SA before, but never I've never done MIT ->
>GPL. I know that (1) the law is not super clear about this stuff and
>different lawyers have different interpretations of what's acceptable,
>and (2) there are some differences between CC licenses (particularly
>moving between them) and software licenses. That said, in the fork I
>did, I included the following in my README.md, names and licenses
>changed to reflect this project:
>
>>[Red Moon](https://github.com/raatmarien/red-moon/) is a derivative of
>[Shades](https://github.com/cngu/shades) by [Chris
>Nguyen](https://github.com/cngu), used under the [MIT
>License](https://opensource.org/licenses/MIT). [Red
>Moon](https://github.com/raatmarien/red-moon/) is licensed under the
>[GPL version 3](https://www.gnu.org/licenses/gpl-3.0.html) or later by
>[Marien Raat](https://github.com/raatmarien).
>
>Someone more knowledgeable than me just pointed out [this
>article](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html).
>
>If @cngu @twckr @Zoraver @stragu @techwebpd and @danialbehzadi are
>willing to license their code under the GPLv3+, it is less work to
>switch. If they don't you'll just need to include notices in various
>places about some of the code being licensed under the MIT license.
>They can give that permission by commenting on this thread with "I give
>permission to use my contributions under the GPLv3 or (at your option)
>any later version."
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/raatmarien/red-moon/issues/26#issuecomment-204784084

- --
Stéphane Guillou
stragu.github.io

Sent from my Fairphone with K-9 Mail. Please excuse my brevity.

You can encrypt our communications by using OpenPGP. My public key
4E211060 is available on the keys.gnupg.net server.
-----BEGIN PGP SIGNATURE-----

iQFXBAEBCgBBOhxrZXliYXNlLmlvL3N0ZXBoYW5lX2d1aWxsb3UgPHN0ZXBoYW5l
X2d1aWxsb3VAa2V5YmFzZS5pbz4FAlcAPGYACgkQRICnFU4hEGAx5Af+JWHIcD6W
bBiuYXGE2wv4lMPXFHj03UirJl2zHa+mNaulX+S5KTEBJ+TEy9HxXh28iuqdR3Vs
dyGlsSh7/fRDDRkhHkoMOXrjC6EGkE/PuQ+QleJD2CD3wwlrFrs0D7GT3h+H03VE
TblSco4/s7HACsedKuc75yO8gDl2hBlKVl1fYtdj2N/zXMkCejeRHGOlOUKmY2QM
MhRepeoJaplDA+XJ9NXZAI4/RV9k/sjGu0of7WNz8irhf0L0mS0S3Yt78EgT2Wpc
Eqzch00Hg8e8zewKeTgSej8Bkyl1lPN9RdEOpmlz7TLX6+EvHm+3gaMYk9lEvsDk
Xqku59IgqBWaTw==
=OZT/
-----END PGP SIGNATURE-----

**Comment by danialbehzadi** [comment]
I am into software licensing and there is nothing to stop changing license from MIT to any other license in the new version if the maintainer wishes so. Anyway, I am super positive about changing to GPLv3+.

On ۳ آوریل ۲۰۱۶ ۲:۱۱:۲۶ (GMT+04:30), "Stéphane Guillou" <notifications@github.com> wrote:
>-----BEGIN PGP SIGNED MESSAGE-----
>Hash: SHA512
>
>I give permission to use my contributions under the GPLv3 or (at your
>option) any later version.
>
>Cheers raatmarien.
>
>On April 3, 2016 5:11:42 AM AEST, smichel17 <notifications@github.com>
>wrote:
>>I've done CC-BY -> CC-BY-SA before, but never I've never done MIT ->
>>GPL. I know that (1) the law is not super clear about this stuff and
>>different lawyers have different interpretations of what's acceptable,
>>and (2) there are some differences between CC licenses (particularly
>>moving between them) and software licenses. That said, in the fork I
>>did, I included the following in my README.md, names and licenses
>>changed to reflect this project:
>>
>>>[Red Moon](https://github.com/raatmarien/red-moon/) is a derivative
>of
>>[Shades](https://github.com/cngu/shades) by [Chris
>>Nguyen](https://github.com/cngu), used under the [MIT
>>License](https://opensource.org/licenses/MIT). [Red
>>Moon](https://github.com/raatmarien/red-moon/) is licensed under the
>>[GPL version 3](https://www.gnu.org/licenses/gpl-3.0.html) or later by
>>[Marien Raat](https://github.com/raatmarien).
>>
>>Someone more knowledgeable than me just pointed out [this
>>article](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html).
>>
>>If @cngu @twckr @Zoraver @stragu @techwebpd and @danialbehzadi are
>>willing to license their code under the GPLv3+, it is less work to
>>switch. If they don't you'll just need to include notices in various
>>places about some of the code being licensed under the MIT license.
>>They can give that permission by commenting on this thread with "I
>give
>>permission to use my contributions under the GPLv3 or (at your option)
>>any later version."
>>
>>---
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/raatmarien/red-moon/issues/26#issuecomment-204784084
>
>- --
>Stéphane Guillou
>stragu.github.io
>
>Sent from my Fairphone with K-9 Mail. Please excuse my brevity.
>
>You can encrypt our communications by using OpenPGP. My public key
>4E211060 is available on the keys.gnupg.net server.
>-----BEGIN PGP SIGNATURE-----
>
>iQFXBAEBCgBBOhxrZXliYXNlLmlvL3N0ZXBoYW5lX2d1aWxsb3UgPHN0ZXBoYW5l
>X2d1aWxsb3VAa2V5YmFzZS5pbz4FAlcAPGYACgkQRICnFU4hEGAx5Af+JWHIcD6W
>bBiuYXGE2wv4lMPXFHj03UirJl2zHa+mNaulX+S5KTEBJ+TEy9HxXh28iuqdR3Vs
>dyGlsSh7/fRDDRkhHkoMOXrjC6EGkE/PuQ+QleJD2CD3wwlrFrs0D7GT3h+H03VE
>TblSco4/s7HACsedKuc75yO8gDl2hBlKVl1fYtdj2N/zXMkCejeRHGOlOUKmY2QM
>MhRepeoJaplDA+XJ9NXZAI4/RV9k/sjGu0of7WNz8irhf0L0mS0S3Yt78EgT2Wpc
>Eqzch00Hg8e8zewKeTgSej8Bkyl1lPN9RdEOpmlz7TLX6+EvHm+3gaMYk9lEvsDk
>Xqku59IgqBWaTw==
>=OZT/
>-----END PGP SIGNATURE-----
>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/raatmarien/red-moon/issues/26#issuecomment-204807956

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smichel17** [comment]
@danialbehzadi Correct me if I'm reading it wrong or if the article is incorrect: according to the [software freedom conservancy article](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html) (section 2.2), if you are using code that is under a permissive license, you should note it in the files. If contributors agree to re-license their code then files can just contain one copyright notice at the top. Of course that doesn't stop Marien from licensing the code she's written under GPLv3+, it's just a little bit more of a pain.

And, it would mean that others could potentially (if with difficulty) extract the MIT-licensed portions and use them under an MIT license, which seems like it kind of defeats the point -- but that's not really an issue since it would make more sense for someone to just fork Shades like Marien did.

Unrelated thoughts: @cngu if you wanted to let this project be 100% GPLv3 but keep Shades MIT, you could provide Shades under a dual license, MIT or GPLv3+.

**Comment by danialbehzadi** [comment]
We do not modifying a MIT licensed code with GPL'd content. We are forking a MIT project and as it allows us, relicense it as GPL. This is a feature of MIT license that you can fork the project and relicense it, either as proprietary or Free software, because MIT is a non-copyleft license.

**Comment by raatmarien** [comment]
Thanks a lot for the help everyone. And thanks for agreeing to relicense to the GPLv3+ @twckr, @stragu and @danialbehzadi!

>Someone more knowledgeable than me just pointed me to [this article](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html).

This seems like a great guide, thanks.

**Comment by raatmarien** [comment]
I've added a header to every code file to reflect the licenses that govern that specific file and who the authors are. I've also updated the README.md and added COPYING, COPYING.MIT and COPYING.GPL to explain the new license situation.

I hope this is sufficient to relicense Red Moon to the GPLv3+, any pointers on what I should add or change are welcome!
