### ISSUE TITLE
Crashes when turned on Moto G 2ng gen stock 6.0.

### ISSUE THREAD

**Issue by pypcz** [raatmarien/red-moon#3]
Crashes as soon as I press the switch to turn it on and keeps on crashing in the background every fes seconds.

**Comment by raatmarien** [comment]
Thanks for letting me know! I'm looking into it.

**Comment by raatmarien** [comment]
Turns out the app wasn't properly requesting permissions for Android 6.0 and above, since drawing over other apps is considered a dangerous permission. I fixed it now, thanks for letting me know about the issue.
