### ISSUE TITLE
Can't add the widget on the desk

### ISSUE THREAD

**Issue by Siltaar** [raatmarien/red-moon#31]
Using Android 5.1 from Fairphone 2 and last f-droid available RedMoon : 2.6.2

If I grab the RedMoon widget to slide it on a desk panel, the widget is dropped on the panel, but never appears on it. I tried several times…

**Comment by raatmarien** [comment]
Thanks for letting me know!

Could you tell me if you are using the standard launcher or something else and how much space you have left on the desk panel you tried to drop it on?

For a temporary work around, you could try using the short cut of Red Moon. Sorry for the inconvenience.

**Comment by Siltaar** [comment]
Hi,

It is the standard launcher.

My available widget list tells me that RedMoon widget needs 1x1 scare. So I'm aiming at a 1x1 empty space to drop it on. 

Twilight is providing 1x2 and 1x1 widgets, but my opinion is that 1x1 is enough.

**Comment by raatmarien** [comment]
Okay, thanks for letting me know!

I'll look into it.

**Comment by Siltaar** [comment]
Fixed with new release 2.7.1.

**Comment by raatmarien** [comment]
Okay, great!
