### ISSUE TITLE
Provide feedback on the acquired location

### ISSUE THREAD

**Issue by Siltaar** [raatmarien/red-moon#32]
Hi,

I would like to use the Sun times to enable and disable RedMoon. I activated once my location feature then activated RedMoon auto-turn-on feature.

Here, I feel I miss a feedback from RedMoon to show me which position was acquired if any.

**Comment by raatmarien** [comment]
Thanks for the feedback!

I agree, and I'm working on changing this in the next update. See #29.

**Comment by smichel17** [comment]
@Siltaar @raatmarien this issue can be closed with the release of 2.7.0?

**Comment by raatmarien** [comment]
I think so. If you think this should be reopened, let me know @Siltaar!

**Comment by Siltaar** [comment]
Seen Location feedback (can't acquire one, but it may be my bad).
