### ISSUE TITLE
Contributing Translations

### ISSUE THREAD

**Issue by DistantParadox** [raatmarien/red-moon#37]
I am able to contribute translations to Chinese, which would widen the user-base, but I am not sure how this could be done.  Do you have any suggestions?

**Comment by raatmarien** [comment]
Hey, that's great! Thanks a lot!

To translate:

If you are familiar with git:
* Fork this repo
* In your fork, copy [app/src/main/res/values/strings.xml](https://github.com/raatmarien/red-moon/tree/master/app/src/main/res/values) to app/src/main/res/values-<your country code>/strings.xml.
* Translate the strings that aren't marked with a 'translatable="false"' flag
* Submit a pull request

If you'd rather just translate, you can translate the strings in [this file](https://github.com/raatmarien/red-moon/tree/master/app/src/main/res/values), send it to me, and then I will commit it into the repo.

**Comment by M2ck** [comment]
@raatmarien Please give a try to Crowdin, IMHO this is the best translation website and it's free of charge for Open Source projects: [Open Source Project Setup Request Form](https://crowdin.com/page/open-source-project-setup-request).
Then I would be glad to translate Red Moon in French :smiley:

**Comment by M2ck** [comment]
In additionally with my previous post, [Weblate](https://weblate.org/en/) is a good translation website too.

**Comment by raatmarien** [comment]
>@raatmarien Please give a try to Crowdin, IMHO this is the best translation website and it's free of charge for Open Source projects: Open Source Project Setup Request Form.
Then I would be glad to translate Red Moon in French :smiley:

Thanks for the suggestion, handling all the translations manually is indeed far from ideal.

>In additionally with my previous post, Weblate is a good translation website too.

Thanks to your comment I have been looking into different translation websites and have found Weblate too :smile:. I've actually received hosting there just now and I'm setting it up with github now. See: https://hosted.weblate.org/projects/red-moon/

**Comment by M2ck** [comment]
>Thanks to your comment I have been looking into different translation websites and have found Weblate too :smile:. I've actually received hosting there just now and I'm setting it up with github now. See: https://hosted.weblate.org/projects/red-moon/

Perfect :+1: 
Red Moon will speak French soon!

**Comment by smichel17** [comment]
This issue can probably be closed :)

**Comment by raatmarien** [comment]
@M2ck thanks for translating! 

@smichel17 indeed.

**Comment by M2ck** [comment]
@raatmarien you're welcome. Did you aware of strings missing, related to the type filter menu & toggle mode dialog, on Weblate?

**Comment by raatmarien** [comment]
No I wasn't, thanks. I found the cause: https://docs.weblate.org/en/latest/formats.html#android-string-resources and will be fixing it soon.

**Comment by DistantParadox** [comment]
Awesome.  Currently working on Chinese (Mandarin Simplified) translations.
