### ISSUE TITLE
Option to disable button backlight

### ISSUE THREAD

**Issue by dillbyrne** [raatmarien/red-moon#39]
Hi raatmarien . Great job on the app. Thank you for your work

If you have the time could you add an option to disable the button backlight. The [dimmer app](https://github.com/giraffine/Android-Project) on F-Droid already has code to do it.

https://github.com/giraffine/Android-Project/blob/d4d02c86706f506d1a8b1d03a2ff61657a28e368/Dimmer/src/giraffine/dimmer/Mask.java

**Comment by raatmarien** [comment]
Hey, thanks for the suggestion and thanks for the link!

I will attempt to implement this when I have the time.

**Comment by dillbyrne** [comment]
Thanks, I appreciate it.

**Comment by raatmarien** [comment]
Red Moon now dims the hardware buttons when the filter is on. I haven't been able to test it, since I don't own any devices with hardware buttons, so please let me know if it doesn't work when you have updated to v2.7.3.

Thanks!

**Comment by smichel17** [comment]
I have a galaxy s4 and will test when this version comes to f-droid.

**Comment by raatmarien** [comment]
Great, thanks!

**Comment by dillbyrne** [comment]
@raatmarien it is working great for me on the galaxy s2. :+1:

**Comment by raatmarien** [comment]
Nice. Thanks for testing :+1:

**Comment by smichel17** [comment]
Doesn't seem to have any effect for me. I don't particularly mind because my hardware buttons are not very bright so I never thought to dim them in the first place. I'm also using a deodexed TouchWiz ROM so xposed will work, which is a little flaky at times, so I would not be surprised if that's why it does not work. That part of the dimmer app doesn't work either.

**Comment by raatmarien** [comment]
Thanks for testing it @smichel17. Weird that it doesn't work for you, but as you said I don't think it would be easy to fix, since it doesn't work with the Dimmer app either.

**Comment by di72nn** [comment]
Hi.
Thanks for the feature, but it has a very nasty side-effect: the app disables keyboard backlight on devices with a physical QWERTY keyboard, which renders the keyboard almost unusable (it is hard to blind-type on a mobile keyboard).
Please add an option to disable the feature.

**Comment by smichel17** [comment]
@di72nn could you create a new issue for this so it doesn't get lost? Thanks.
