### ISSUE TITLE
Version 2.2 still crashes on CM 13 (Marshmallow)

### ISSUE THREAD

**Issue by Mr5quid** [raatmarien/red-moon#4]
Hi there !

I saw that you said that the bug had been fixed in the other tickets but I've just upgraded to 2.2 and nothing has changed : It crashes when trying to enable Redmoon.

Your app looks promising I hope I will be able to try it soon :)

**Comment by Bugsbane** [comment]
I have v2.2 (from FDroid) crash the moment I enable it on Android 6.0.1 on a Nexus 5x, as well.

**Comment by raatmarien** [comment]
Hey guys, sorry for the inconvenience. Sadly, I wasn't able to fix that bug in time for f-droid to incorporate it into its repository update. 

The bug fix will be incorporated in version 2.2.1, which will be available the next time f-droid syncs it's repository.  The fdroiddata repository has already been updated with the new version (https://gitlab.com/fdroid/fdroiddata/commit/16b6ac66f6b9e8c32c97dea842a86a42298fdee8). 

Please let me know if any issues persist, when v2.2.1 is available. I don't have an android 6.0 device myself, so it really helps that you guys let me know about any problems.

**Comment by raatmarien** [comment]
V2.2.1 with the bug fix is now available on f-droid.

**Comment by Bugsbane** [comment]
Just updated. Works perfectly now. THANK YOU!

**Comment by raatmarien** [comment]
No problem :)
