### ISSUE TITLE
[Backend] Update preference implementation

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#40]
There's some duplicate code for changing preferences. I was looking into refactoring this, and came across some information that the approach used right now is deprecated. The [new approach](https://developer.android.com/guide/topics/ui/settings.html) uses an XML file for each fragment, so you can (for example) add `android:dependency="mSwitch"` and the setting will automatically gray out if the main switch is disabled, without needing to write any custom java.

FWIW, the code is generally really nice. I don't know much Java or Android-specific stuff (but I do know C -- pretty close), and it was very clear what was going on.

**Comment by raatmarien** [comment]
This is very useful, thanks!

I will use this in the future for settings that depend on a switch or a checkbox. However, depending on the top switch is impossible, since the android:dependency tag only allows referencing other dependencies. The top switch isn't a preference, but a menu item, because the app bar doesn't allow preferences.

**Comment by smichel17** [comment]
I wonder if there's a way to "cheat" here. Is it possible to make a "preference" that is not actually displayed, that updates (using the old method) whenever the top switch does? (and then make others depend on it)

**Comment by smichel17** [comment]
If you can't have preferences that are not displayed, is it possible to attach a state to one of the currently stateless items (email or visit project page) without changing how that item is displayed?

**Comment by raatmarien** [comment]
>I wonder if there's a way to "cheat" here. Is it possible to make a "preference" that is not actually displayed, that updates (using the old method) whenever the top switch does? (and then make others depend on it)

Hmm, I think this is possible, I'll try letting it depend on a key without a preference.

**Comment by raatmarien** [comment]
I tried letting it depend on just a key, but it turns out that android:dependency needs an existing preference.

It may be possible to declare a preference without showing it, but I think it would be harder and less clear than just enabling/disabling the preferences manually in the code.

**Comment by smichel17** [comment]
Having to loop through settings and enable/disable them seems like an impediment to making changes; with dependencies declared, it's easy to rearrange, add or delete prefs. Something something maintainable code.

Is it possible to make a visible preference, and put it on a screen that there is no GUI control to access?

An alternative that I don't like very much: You could add a preference at the very bottom.

Type: Switch
Label: "Enable Red Moon"
Secondary text: "Change this setting with the top switch"
Value: Copies the top switch value
Is always disabled / grayed out.

**Comment by smichel17** [comment]
Emphasis mine.

>#### android:enabled

>Whether the Preference is enabled.

>Must be a boolean value, either "`true`" or "`false`".

>_This may also be a reference to a resource (in the form "`@[package:]type:name`") or theme attribute (in the form "`?[package:][type:]name`") containing a value of this type._

>This corresponds to the global attribute resource symbol `enabled`.

Is this useful? Maybe onShadesPowerStateChanged() could set a resource or attribute that all the relevant settings could depend on?

Related: #42

**Comment by raatmarien** [comment]
The android:enabled tag is only checked when the view is created, so it can't be used to dynamically change the enabled state of a preference.

I believe that in this case it is better to just enable/disable the preferences in the code. That way it is clear when preferences are enabled/disabled and it will be at most adding one line of code for every preference when adding new preferences.

**Comment by smichel17** [comment]
>The android:enabled tag is only checked when the view is created, so it can't be used to dynamically change the enabled state of a preference.

Pfft. Ah well, was worth a shot.

>I believe that in this case it is better to just enable/disable the preferences in the code. That way it is clear when preferences are enabled/disabled and it will be at most adding one line of code for every preference when adding new preferences.

Okay. Closing this.
