### ISSUE TITLE
[Code cleanup] getShadesPowerState()

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#42]
On [line 85 of ShadesPresenter.java](https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/presenter/ShadesPresenter.java#L85), when the FAB is clicked, it checks to make sure ShadesPowerState is on. This check is unnecessary because the FAB will not display if ShadesPowerState is off.

I don't know if there are more checks like this scattered around the code (notifications? automatic toggle?), but if there are they can probably all be removed. The only actions possible while PowerState is off are changing the theme, sending feedback via email, and visiting this github page, none of which change their behavior based on PowerState.

There's already an onShadesPowerStateChanged() function -- it should be all that is needed, I think.

**Comment by raatmarien** [comment]
Good find, I fixed it. I didn't find any more of these, but if you see any let me know!
