### ISSUE TITLE
Support Android N's quick tile API

### ISSUE THREAD

**Issue by jluttine** [raatmarien/red-moon#46]
I'm having difficulties writing this feature proposal because I don't know the terms.. Currently, redmoon appears in the notification panel. At least on my Cyanogenmod, there's another similar panel which shows square icons for wifi, brightness, settings, volume, location etc. Could redmoon be moved there instead (what's the name of that panel???)? One nice square icon among the others. Then, one press to enable/disable (pause/unpause) and a long press to open the app itself. Then it wouldn't need to appear in the notification panel anymore either.

Does this make sense?

**Comment by raatmarien** [comment]
Thanks for the suggestion. 

Do you mean the [quick settings tray](http://dxdkxqkkk0kvy.cloudfront.net/wp-content/uploads/2014/07/android-l-settings-tray.jpg)? I agree it would be great to have a Red Moon icon there, but this tray is only accessible to the system. As far as I know it is impossible to add an non-system app icon or toggle there.

**Comment by jluttine** [comment]
Yep, quick settings tray. :+1: And yes, I have no idea whether it is possible to non-system app icons there or not. I hope it is possible..

**Comment by smichel17** [comment]
@jluttine I'm pretty sure you'd need to modify the android/CM system to do that. The closest we could reasonably get is something silly like Red Moon watching whether bluetooth is on or off and turning itself on and off based on that (which, I don't think we really want to support).

**Comment by M2ck** [comment]
It will be possible with Android N, not before.
Title should be edited by "Support Android N's quick tile API".

Source: [Android N documentation](https://developer.android.com/preview/api-overview.html#tile_api)

**Comment by raatmarien** [comment]
>It will be possible with Android N, not before.
Title should be edited by "Support Android N's quick tile API".

Aha, I didn't know that this was added. Thanks for the information.

**Comment by M2ck** [comment]
>Aha, I didn't know that this was added. Thanks for the information.

You're welcome :)
