### ISSUE TITLE
On/Off Switch issue

### ISSUE THREAD

**Issue by SapienTech** [raatmarien/red-moon#50]
Switch not initialized to ON when red-moon starts from boot.

**Comment by smichel17** [comment]
Could you give a little more detail? When you first install the app, it should be in the OFF position. After that, it should remember the position across reboots.

**Comment by raatmarien** [comment]
Thanks for reporting this issue.

I can't seem to replicate Red Moon having the incorrect state at boot, but I'm able to replicate it when updating to a new version. Is it possible that it was the first time you opened Red Moon after updating it?

**Comment by raatmarien** [comment]
Since there have been a few changes to how Red Moon handles the state after a boot, I'm closing this issue for now under the assumption that it isn't relevant anymore. If you still experience this problem, feel free to reopen it.

**Comment by SapienTech** [comment]
@raatmarien @smichel17 hi there, happened to not see that you guys responded! It may have been from an update, i'll double check now to see if the new updates have fixed things. I haven't seen the error in a while so i believe its fixed!
