### ISSUE TITLE
UI Tweaks for RTL locales

### ISSUE THREAD

**Issue by danialbehzadi** [raatmarien/red-moon#56]
There are some twaeks in UI for RTL languages. For example, handles should move from right to left for increasing the value and the resume button should point to the left

This is what it looks like now in Persian locale:
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/3658678/14600920/66489384-0574-11e6-9b7a-1fd24a3dbcc7.png)

This is what it should look like:
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/3658678/14601052/1b25be76-0575-11e6-8163-09221d6a03b5.png)

**Comment by raatmarien** [comment]
Thanks for letting me know, I didn't know that.

I will look into fixing it.

**Comment by smichel17** [comment]
Here's the relevant page from the material guidelines. https://www.google.com/design/spec/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines

**Comment by raatmarien** [comment]
I mirrored the resume icons in RTL layouts, however I can't seem to replicate the issue with the seekbars on your first image. On my device and my emulators, the seekbars progress to the right like in the second image. Could you tell me what android version and what version of Red Moon you are using @danialbehzadi ? Thanks.

**Comment by danialbehzadi** [comment]
Android version: 4.4.4 (cyanogenmod 11 20160404)
Red moon version: 2.7.3 F-Droid) 

On ۱۸ آوریل ۲۰۱۶ ۱۷:۴۲:۵۱ (GMT+04:30), Marien Raat <notifications@github.com> wrote:
>I mirrored the resume icons in RTL layouts, however I can't seem to
>replicate the issue with the seekbars on your first image. On my device
>and my emulators, the seekbars progress to the right like in the second
>image. Could you tell me what android version and what version of Red
>Moon you are using @danialbehzadi ? Thanks.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/raatmarien/red-moon/issues/56#issuecomment-211374349

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smichel17** [comment]
In the code in master, the FAB is gone and % signs should now display on the correct side of numbers (I'm not sure which side is the correct side, but `string.format()` should know).

For sliders, let's wait until after I've consolidated them to all use the same layout code (#70).

**Comment by smichel17** [comment]
@danialbehzadi When you get a chance, could you download v2.10.0 (should be out on fdroid/gplay soon) and see if this is still an issue?

**Comment by danialbehzadi** [comment]
Unfortunately I've upgraded my phone to LineageOS 14.1 (Android 7.1 Nougat) and can not check this. Even the older versions are aligned correctly on newer AOSP releases.

در ۳ مارس ۲۰۱۷ ۱۱:۵۶:۴۹ (GMT+03:30)، smichel17 <notifications@github.com> نوشت:
>@danialbehzadi When you get a chance, could you download v2.10.0
>(should be out on fdroid/gplay soon) and see if this is still an issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/raatmarien/red-moon/issues/56#issuecomment-283895066

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smichel17** [comment]
I tried it on an android 4.2 emulator, Arabic locale, and everything was correctly mirrored. I'm going to close this, and if anybody comes across other places where RTL is not working as it should, feel free to open another issue.

**Comment by ahangarha** [comment]
From where can I change the app's language into Persian?

I have made some improvements in translation as well. But I cannot find where the language setting is!

I have installed the app from F-Droid and currently using v3.3.2.

**Comment by smichel17** [comment]
There is no setting; Red Moon will use your phone's language.
