### ISSUE TITLE
Preview filter when adjusting sliders

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#59]
- [ ] Filter turns on while sliders are being adjusted

When the filter is active, you can see immediately what happens as you adjust the sliders. When the app is off, you need to turn it on to see; real time feedback on what the filter is going to look like would be really useful.

**Comment by raatmarien** [comment]
This seems very useful, but I'm not sure how to present how the filter would look. Would a simple rectangular surface with the colour that the background colour of Red Moon will become when the filter is on suffice? Or should it display some sample text in white on black and black on white with a filter applied to it, to better show how it will look with the filter on?

**Comment by smichel17** [comment]
I was thinking that the filter would turn on for the whole screen, with no fade.

**Comment by raatmarien** [comment]
I finally got around to implementing this. I will include it in the next update.
