### ISSUE TITLE
Can't press on the Install button while running red moon

### ISSUE THREAD

**Issue by sbruder** [raatmarien/red-moon#6]
If I want to install an application over F-Droid or directly over an APK and running red moon while I want to install an application, I can't press on the install button, but if I then switch red moon of, I can press on Install. I haven't Google Play Services, so I can't test if it appears on an installation from Google Play, too.

**Comment by raatmarien** [comment]
Hey, thanks for letting me know. 

As a security measure, Android blocks the install button when an overlay (such as this filter)  is running. In the feature I will look into automatically pausing the filter when an install prompt appears.

**Comment by twckr** [comment]
Same problem for me with F-Droid. Installations using the Google Play Store are possible without limitations.
I'm on Android 4.2.2

**Comment by twckr** [comment]
Maybe the label "bug" would be more appropriate... ;-)

**Comment by raatmarien** [comment]
You're right, I'll change it. 

However I'm not sure how it can be solved, since android will block the install button when any overlay is drawn. One solution would be to monitor which app is running and automatically pause the filter when an install dialog is open, however constantly checking the running app will degrade battery life and I'm not sure how to go about it.

**Comment by twckr** [comment]
@raatmarien , I just found this page which underlines your words:
[https://f-droid.org/forums/topic/blocked-install-button/](https://f-droid.org/forums/topic/blocked-install-button/).

Maybe it's enough to put a little reminder in the "Settings" section of the app?

**Comment by raatmarien** [comment]
>Maybe it's enough to put a little reminder in the "Settings" section of the app?

Since the whole app is the settings screen, a permanent warning there might be clutter the view. Do you think a dialog when the user turns on the filter for the first time would suffice?

**Comment by twckr** [comment]
Dialog is a good idea. But I'm not quite sure if one remembers the dialog after some weeks or so...

**Comment by twckr** [comment]
Maybe changing "Running" to "Running. Pause or stop to install apks" would help as it can always be seen in the notifications menu

**Comment by raatmarien** [comment]
>Maybe changing "Running" to "Running. Pause or stop to install apks" would help as it can always be seen in the notifications menu

That seems like a great idea. Do you think an toast with a warning every time the filter is turned additionally on would be nice, or would that be overdoing it?

On a side note, I just noticed that installing also won't worked with the filter paused, it will only work when the filter is stopped, but that could probably be fixed.

**Comment by twckr** [comment]
Toast is a very good idea as well! 

Am 20. März 2016 18:53:54 MEZ, schrieb raatmarien <notifications@github.com>:

**Comment by raatmarien** [comment]
The app now displays a warning toast, when the filter is first opened in the lifetime of the activity and the notification mentions that the filter should be paused when installing APKs. Furthermore, users should now be able to install APKs while the filter is paused. Hopefully this strikes a balance between informing the user and not being annoying :).

@twckr Could you please check my German [here](https://github.com/raatmarien/red-moon/blob/c12b64f2d540e6184799981d2aa1cc6c3d2c745b/app/src/main/res/values-de/strings.xml#L6) and [here](https://github.com/raatmarien/red-moon/blob/c12b64f2d540e6184799981d2aa1cc6c3d2c745b/app/src/main/res/values-de/strings.xml#L12)?
