### ISSUE TITLE
Automatically pause filter in some apps (APK Installer)

### ISSUE THREAD

**Issue by raatmarien** [raatmarien/red-moon#64]
Originally discussed in #61.

> - Automatically pause when installing APKs
Darker detects when an APK is attempting to install and temporarily pauses.

This would indeed be very useful, and I've been looking into how to accomplish this. It seems that up to Android Lollipop (API 21) it was fairly easy to get the info of the foreground app with [ActivityManager.getRunningTasks](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningTasks(int)), however as of API 21+ this only returns 'non sensitive' tasks, making it unusable for this purpose. 

According to [this StackOverflow answer](http://stackoverflow.com/a/33828821) a workaround on later versions of Android is using android UsageStatsManager and filter out the last used application. A problem with this approach is that UsageStatsManager isn't implemented on Samsung phones according to the comments on that question.

Lastly I'm not sure how Red Moon would register changes to the foreground activity. There doesn't seem to be a listener framework for the UsageStats or the ActivityManager and constantly polling for changes may be a drain on the battery life of a phone.

That said, I'm quite a fan of this feature. I think it would be a huge usability improvement (especially for F-Droid users). However it seems that it would be quite complex and time consuming to implement this correctly, which I don't have right now. If someone else is willing to implement this, I would love to see a pull request :smile:.

**Comment by smichel17** [comment]
Here's an idea, albeit one that makes me a little uncomfortable.

We could allow users to set red moon as the default application for installing apks, rather than the package installer. Then red moon disables the filter, calls the package installer so the user can install the apk. When the package installer completes, red moon will automatically return to the foreground. Then it can re-enable the filter and close itself. There's an Antivirus app that comes with the galaxy S7 that does this.

**Comment by pylerSM** [comment]
^^ this is best idea. I maybe try to implement it :D

**Comment by raatmarien** [comment]
I've implemented a solution to this in [v2.9.0](https://github.com/raatmarien/red-moon/releases/tag/v2.9.0). If you enable "Automatic suspend" in this version, Red Moon polls the current package every second that the filter is active and the screen is on and suspends the filter when a 'protected' app is detected. See: efa1e05bc70fa29f00c697e3ab00b894051b78f6.

**Comment by pylerSM** [comment]
fine :)
