### ISSUE TITLE
Cannot find location

### ISSUE THREAD

**Issue by kylenoteboom** [raatmarien/red-moon#67]
Trying to find my location when location services are turned off gives me a toast saying I need to enable location services.

I enabled them, and it's been searching for my location this whole day by now.

Might be a problem with my shitty GPS, but I can't manually set my location either.

What do?

**Comment by smichel17** [comment]
Probably the easiest thing is just setting the on/off times automatically.

**Comment by raatmarien** [comment]
Thanks for reporting this bug!

Do you have a network location back end, for example Google Play Services or mg UnifiedNlp, installed and enabled?

**Comment by kylenoteboom** [comment]
I've got Google Play Services.
The `Location` settings has a `Location mode` option, which is set to `High accuracy`, with the following description: `Use GPS, Wi-Fi and mobile networks to determine location`

**Comment by smichel17** [comment]
Do other apps that require your location work?

**Comment by kylenoteboom** [comment]
Yes, but with problems as well. As I mentioned above, my GPS sucks. Google Maps was able to locate me exactly 3 times on a ~35 minute bike ride.

Regardless, an option to manually set your location should be available in my opinion.

**Comment by smichel17** [comment]
It seems like this is probably a problem with your GPS then, not Red Moon so I think this issue can be closed. We can continue discussing the ability to set your location in #5.

In the meantime, the best workaround would be to set on/off times manually.

**Comment by raatmarien** [comment]
Indeed, let's discuss manual setting of location in #5 :+1:
