### ISSUE TITLE
Overlays and SuperSU

### ISSUE THREAD

**Issue by pylerSM** [raatmarien/red-moon#68]
Can you support this https://su.chainfire.eu/#updates-tapjacking?

**Comment by smichel17** [comment]
Seems like a reasonable thing to support. We should not request superuser access on first run, though. 

It should be a setting that has its own screen to explain why we are requesting SU access, like 'magnification gestures' here: https://material.google.com/patterns/settings.html#settings-labels-secondary-text

**Comment by StefanBrand** [comment]
Hello! :)

Why is this closed? In the latest version on F-Droid (2.9.2) I still have to disable Red Moon manually every time an app needs root access.

**Comment by raatmarien** [comment]
Do you have 'Automatic suspend' enabled? If so, what superuser app (with what package name) do you use?

**Comment by StefanBrand** [comment]
I don't now (yet). I'm running a FP1 with KitKat 4.4.2. on a Mediatek MT6589 chipset.

I opened a new topic on the Fairphone forum and will let you know, when I have a definite answer.

https://forum.fairphone.com/t/which-superuser-manager-app-comes-preinstalled-with-kitkat/25865?u=stefan
