### ISSUE TITLE
Cannot start the application "Red Moon has stopped"

### ISSUE THREAD

**Issue by Varlorg** [raatmarien/red-moon#7]
Hi,

when I try to launch the application I got the message " Unfortunately, Red Moon has stopped".
My phone is Motorola moto g 4G with android 4.4.4 (XT1039).

Using USB Debugging, here the log:
E/VdcInflateDelegate(14075): Exception while inflating <vector>
E/VdcInflateDelegate(14075): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate(14075): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
E/VdcInflateDelegate(14075): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
E/VdcInflateDelegate(14075): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:829)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:303)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:178)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
E/VdcInflateDelegate(14075): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
E/VdcInflateDelegate(14075): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/VdcInflateDelegate(14075): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/VdcInflateDelegate(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/VdcInflateDelegate(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379)
E/VdcInflateDelegate(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
E/VdcInflateDelegate(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
E/VdcInflateDelegate(14075): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
E/VdcInflateDelegate(14075): 	at com.jmstudios.redmoon.activity.ShadesActivity.onCreate(ShadesActivity.java:35)
E/VdcInflateDelegate(14075): 	at android.app.Activity.performCreate(Activity.java:5248)
E/VdcInflateDelegate(14075): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
E/VdcInflateDelegate(14075): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
E/VdcInflateDelegate(14075): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
E/VdcInflateDelegate(14075): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/VdcInflateDelegate(14075): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
E/VdcInflateDelegate(14075): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate(14075): 	at android.os.Looper.loop(Looper.java:136)
E/VdcInflateDelegate(14075): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
E/VdcInflateDelegate(14075): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate(14075): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate(14075): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/VdcInflateDelegate(14075): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/VdcInflateDelegate(14075): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(14075): Shutting down VM
W/dalvikvm(14075): threadid=1: thread exiting with uncaught exception (group=0x416b1d40)
E/AndroidRuntime(14075): FATAL EXCEPTION: main
E/AndroidRuntime(14075): Process: com.jmstudios.redmoon, PID: 14075
E/AndroidRuntime(14075): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jmstudios.redmoon/com.jmstudios.redmoon.activity.ShadesActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
E/AndroidRuntime(14075): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
E/AndroidRuntime(14075): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime(14075): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime(14075): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
E/AndroidRuntime(14075): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14075): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14075): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime(14075): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14075): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14075): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(14075): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(14075): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(14075): Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379)
E/AndroidRuntime(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
E/AndroidRuntime(14075): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
E/AndroidRuntime(14075): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
E/AndroidRuntime(14075): 	at com.jmstudios.redmoon.activity.ShadesActivity.onCreate(ShadesActivity.java:35)
E/AndroidRuntime(14075): 	at android.app.Activity.performCreate(Activity.java:5248)
E/AndroidRuntime(14075): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
E/AndroidRuntime(14075): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
E/AndroidRuntime(14075): 	... 11 more
E/AndroidRuntime(14075): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(14075): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(14075): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(14075): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime(14075): 	... 25 more
E/AndroidRuntime(14075): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
E/AndroidRuntime(14075): 	at android.content.res.Resources.loadDrawable(Resources.java:2099)
E/AndroidRuntime(14075): 	at android.content.res.Resources.getDrawable(Resources.java:700)
E/AndroidRuntime(14075): 	at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
E/AndroidRuntime(14075): 	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
E/AndroidRuntime(14075): 	at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
E/AndroidRuntime(14075): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
E/AndroidRuntime(14075): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
E/AndroidRuntime(14075): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
E/AndroidRuntime(14075): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
E/AndroidRuntime(14075): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
E/AndroidRuntime(14075): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
E/AndroidRuntime(14075): 	... 28 more
E/AndroidRuntime(14075): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
E/AndroidRuntime(14075): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime(14075): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime(14075): 	at android.content.res.Resources.loadDrawable(Resources.java:2095)
E/AndroidRuntime(14075): 	... 38 more
W/ActivityManager( 1023):   Force finishing activity com.jmstudios.redmoon/.activity.ShadesActivity

**Comment by raatmarien** [comment]
Hey, thanks for letting me know and especially for the stack trace!

Could you tell me what version of Red Moon you are running? 

Thanks.

**Comment by Varlorg** [comment]
Sorry, I forgot to precise the version. It was with the 2.1, I didn't see that new version were available, I tried with 2.2 and 2.2.1 and It is working with these two versions.

**Comment by raatmarien** [comment]
No problem, happy it works now :)
