### ISSUE TITLE
Add changelog link to fdroid repo

### ISSUE THREAD

**Issue by thigg** [raatmarien/red-moon#71]
It would be nice if one could read the changelog before updating.

**Comment by raatmarien** [comment]
Great point!

I've submitted a Merge Request to the main F-Droid data repository to add the changelog to the metadata. When it is merged, it will only take few days until it shows up on F-Droid.

https://gitlab.com/fdroid/fdroiddata/merge_requests/1585

**Comment by raatmarien** [comment]
It has been merged already. The changelog will show up on F-Droid in a few days.
