### ISSUE TITLE
Lower brightness per filter

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#75]
`lower brightness` looks like it is part of the settings for a filter, but is actually independent of the selected filter. 

Options to fix are
- making it per-filter
  - Argument for this: there is a filter I use (for viewing color-sensitive media in a room with lights off) which does not change the red levels but does darken the screen; I use it exclusively after I've turned my phone's hardware brightness to minimum.
- moving the setting
  - Argument for this: it's how filters work right now; the other reduces flexibility of the default config.

I think we should go with the first option. The default filter should not have `lower brightness` enabled. The bed reading filter should. If the user changes this setting, the current filter is updated instead of displaying `custom` like if you changed any of the other filter settings.

**Comment by smichel17** [comment]
As additional argument for option 1, I'll add that it suits my pattern of use rather well: When the filter turns on, I almost always set it to default and automatic brightness right away. Then later when I'm going to bed, if I want to use my phone in the dark, I'll change to my "darker" filter and manually lower the brightness.

**Comment by raatmarien** [comment]
When I first implemented profiles, I thought it would only be for the colour/transparency of the filter, so I haven't made it very flexible. I agree that it is confusing that Lower brightness is under the same header, but not affected by the profile.

Option 1 seems like the best solution to me, however it will require a change in the database of the profiles. I will look into changing this database. I'm however not sure what the Lower brightness setting of the profiles the user has made in old versions should be. Should it be off for all these profiles, or should it be the value of Lower brightness that the user has set when they install the new version of Red Moon. What do you think?

**Comment by smichel17** [comment]
Having things change without taking any action (many users auto-update) is diruptive; I would use whatever the user has set when they update for all filters as the default value.

For new installs, definitely off for `Default`, but maybe on for `Bed reading`? Or we could just let the user enable it in a custom profile if they want it. I'm not sure about that one.

**Comment by smichel17** [comment]
Since this will require changing the format of profile storage, we should consider whether it would be better to stick with using the sharedPreferences or just migrate to a database.

**Comment by smichel17** [comment]
Looked into Android databases a little and they would be overkill for our needs. SharedPrefs + JSON is totally sufficient.

**Comment by smichel17** [comment]
Done in #118; will be released in v3.0.0.
