### ISSUE TITLE
Send public Intents when Red Moon pauses/resumes

### ISSUE THREAD

**Issue by revuwa** [raatmarien/red-moon#80]
Thanks for this great app, which I really like to use.

Especially I like the automatic toggle mode. Usually I switch my device in airplane mode for the night.
So it would be very cool if there would be a airplane mode toggle, which automatically activates on the custom automatic red-moon toggle times.

For me this would be an awesome feature. Is there anybody else, who agrees about this suggestion?

Just as a visual illustration:
![flightmode](https://cloud.githubusercontent.com/assets/7300276/18009164/6cc02ef0-6bab-11e6-9934-94422b49d02c.png)

**Comment by smichel17** [comment]
One of the things that makes Red Moon great is that it is very simple to set up and use. Every feature and setting you add makes it harder to use, because it is another thing you need to think about before you can get straight into using the app.

As I understand it, Red Moon is made for users who want to use their phone in the dark, either to make it easier on their eyes or help with sleep. I'm happy to be proved wrong, but this feature suggestion looks to me like it would only be used by a small portion of Red Moon users. I wouldn't want to make the app harder to use for most people to make it slightly more useful for a small portion.

That said, I think there is a way to support this feature without adding any additional settings. If red moon sent an intent when turning on/off the filter, then you could use an app like Tasker to turn on Airplane mode whenever it receives the intent.

**Comment by revuwa** [comment]
@smichel17 Thanks for your response.

> [...] I'm happy to be proved wrong, but this feature suggestion looks to me like it would only be used by a small portion of Red Moon users. [...]

This was the question, I would like to ask.

First, your intent based idea sounds great to me. But I can't find an open source Tasks alternative. I just found LibreTasks https://f-droid.org/repository/browse/?fdid=libretasks.app which doesn't seems to support airplane toggle, only wi-fi and BT, and only defined triggers, not really intents.

I don't know. If the suggested functionality isn't generally rejected, what if features like this will be just "hidden" from common users. For example by adding a flight mode point in the [toggle mode] menu, or with an advanced menu after long-press on the floating action button or something?

**Comment by pylerSM** [comment]
Togglin Airplane mode requires root. If you have root and use Tasker I think @raatmarien have no problems to add code which fires intents for " red-moon toggle times" events (start/stop)

**Comment by smichel17** [comment]
>First, your intent based idea sounds great to me. But I can't find an open source Tasks alternative. I just found LibreTasks https://f-droid.org/repository/browse/?fdid=libretasks.app which doesn't seems to support airplane toggle, only wi-fi and BT, and only defined triggers, not really intents.

I feel your pain, but this doesn't change my opinion about whether we should support the feature directly. It would be better to take the effort spend developing the feature and add it to LibreTasks instead :)

>I don't know. If the suggested functionality isn't generally rejected, what if features like this will be just "hidden" from common users. For example by adding a flight mode point in the [toggle mode] menu, or with an advanced menu after long-press on the floating action button or something?

The [toggle mode] menu is about controlling *when* the filter toggles, not what happens when it toggles. Having the functionality available but hidden is not something I would support either; it's confusing/unintuitive when people accidentally stumble into it, and the people who would want it can't find it, either!

**Comment by raatmarien** [comment]
I agree that this probably falls out of the scope of Red Moon. It would be better if this functionality was added to LibreTasks.

**Comment by smichel17** [comment]
Red Moon already uses intents to change filter state internally. Are those visible to apps like Libretasks/tasker? If not, I'd consider this issue a request to make them visible.

**Comment by raatmarien** [comment]
Hmm, I didn't think of that. Making the pause/resume intents public would indeed be an option. I'm not sure however if Red Moon should send these intents whenever Red Moon pauses/resumes, or only if it does so automatically. Maybe it should sent different signals for both, so the user has the option to choose? For example, AUTOMATIC_PAUSE and AUTOMATIC_RESUME for automatic changes and MANUAL_PAUSE and MANUAL_RESUME for changes through the UI or the notification.

**Comment by smichel17** [comment]
I would send it for all pause/resume events, for two reasons:

1. It's easier. 
2. At a conceptual level, Red Moon only has the concept of pause/resume (rather than stop/start/pause, like Twilight). Let's stick with that for now and only diverge if it turns out there's a good reason to.

**Comment by smichel17** [comment]
Would making them public would also allow other apps to send them? If not, that's worth looking in to, as well.

As you may be able to tell, I'm a fan of scripting / hook functionality like that as a way to add power for advanced users in a way that isn't overwhelming to new users.

**Comment by smichel17** [comment]
Hooray for #95 which made this possible to do easily and cleanly! :)

**Comment by smichel17** [comment]
Here's the java equivalent of the code used to generate the intent, for anybody using this feature:

```
Intent intent = new Intent();
intent.action = "com.jmstudios.redmoon.RED_MOON_TOGGLED";
intent.putExtra("jmstudios.bundle.key.FILTER_IS_ON", filterIsOn);
sendBroadcast(intent);
```

`filterIsOn` is a boolean that tells you whether the filter has been toggled on or off

**Comment by revuwa** [comment]
Thanks to anybody.
The original title was: "[Feature-request] Airplane mode toggle" and the final result isn't a solution for me, ('cause Tasker isn't open source).
In the meanwhile I found two open source apps which do exactly what I asked for, (toggling airplane mode to specific times):
* https://github.com/yankovskiy/SilentNight
* https://github.com/MBach/AutoAirplaneMode

For everyone with the same (original) intention.

**Comment by smichel17** [comment]
I also try not to install proprietary apps on my phone, and plan on going Google-free as soon as soon as I get my next phone (current phone is too restricted), so I feel your pain, that this is not a solution to the problem.

I think that Red Moon should follow the Unix philosophy: do one thing well (in this case, that thing is filtering the screen at night). I don't think it should be a general timer app, or a "turn your phone off at night" app. Red Moon can be one of several apps to do what you want at night. So, I think it's great that you found SilentNight and AutoAirplaneMode. I hope they suit your needs well.

So, while it is @raatmarien's final decision, in my opinion, the original request is a `wontfix`, and the public intents is a hook for other apps to respond to, if they want. Maybe right now LibreTasks can't toggle airplane mode, but from what I came across when adding the public intent feature, it shouldn't be very hard to do.
