### ISSUE TITLE
Remember last used values for 'custom'

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#82]
1. Change values so filter displays `custom`
2. Select a saved filter
3. Select `custom` again

Current behavior: No change in the active filter
Desired behavior: Filter changes back to what it was in step 1

Then you can make `custom` selectable from the notification, so that you can test out a certain configuration and compare it to existing filters, without continually saving/deleting filters or complicating the app interface.

**Comment by raatmarien** [comment]
I agree that this would be an improvement. I do however think it would require a significant change in the code. I will look into it if I find the time, but if anyone wants to contribute, PRs are welcome.
