### ISSUE TITLE
Do not apply filter to #000000 pixels (for AMOLED screens)

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#83]
It's rather impossible to get any darker or less blue than off. So, in those cases, we should not apply the filter to those pixels.

I don't know if it's possible to detect an AMOLED screen. If not, we should change the dark theme to use a black background and rename the setting, which now also controls this feature, to `AMOLED mode`.

While the current background is slightly prettier than a black background, this is not very important as Red Moon should not be opened often. If you really want to offer the current background, there are 2 ways we could do that, but neither is nearly as simple and elegant as this one.

**Comment by raatmarien** [comment]
>It's rather impossible to get any darker or less blue than off. So, in those cases, we should not apply the filter to those pixels.

I agree that we shouldn't filter black pixels, however due to how Android is set up, it is impossible to accomplish this without a special root mode (See #20).

>I don't know if it's possible to detect an AMOLED screen. If not, we should change the dark theme to use a black background and rename the setting, which now also controls this feature, to AMOLED mode.

>While the current background is slightly prettier than a black background, this is not very important as Red Moon should not be opened often. If you really want to offer the current background, there are 2 ways we could do that, but neither is nearly as simple and elegant as this one.

It would be possible to add an extra theme to Red Moon, that has a completely black background (an AMOLED Dark Theme). However I'm not sure that it would be worth the effort since most users won't spent a lot of time in the Activity of Red Moon and the current dark theme already has a background that is pretty dark.

**Comment by smichel17** [comment]
>I agree that we shouldn't filter black pixels, however due to how Android is set up, it is impossible to accomplish this without a special root mode (See #20).

I guess this is a duplicate of #20, then.

> I'm not sure that it would be worth the effort since most users won't spent a lot of time in the Activity of Red Moon

Totally agreed. The part about the theme was only an idea for how we could incorporate the feature without introducing any additional settings. Since a root mode would require an additional setting anyway, this part is now irrelevant.
