### ISSUE TITLE
Greyscale profile

### ISSUE THREAD

**Issue by pylerSM** [raatmarien/red-moon#84]
It would be nice to provide greyscale (black-white only) color profil out of box, to be enabled by single click.

**Comment by smichel17** [comment]
Dim only, you mean? Possibly. The profiles I use the most are the default profile and one that's like the default but at 70% dim level.

I like the idea of shipping more out-of-the-box profiles, but if we do that I think we should also allow users to remove them. If we do that, we also need to provide a way to reset your profiles back to the way they came.

**Comment by smichel17** [comment]
I'm probably going to tackle #75 and #82 before this, which require making profiles a bit more flexible. Afterwards, this should be easy.

**Comment by smichel17** [comment]
Done in #118
