### ISSUE TITLE
Consider using eventBus instead of onSettingsChangedListener

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#93]
For example, [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/) would make dealing with filter state sooo much easier. It's a relatively small DEX count -- around 350 methods.

**Comment by raatmarien** [comment]
EventBus looks like a very convenient library, especially for broadcasting setting changes. However, I don't have the time to implement it in the codebase.

**Comment by raatmarien** [comment]
This has been done by #95, which has been merged, so I'll close this issue :smiley:
