### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by smichel17** [raatmarien/red-moon#94]
I've been programming recently (on another [app](https://github.com/mpcjanssen/simpletask-android) I use) in [kotlin](http://kotlinlang.org/), which is [much](https://kotlinlang.org/docs/reference/control-flow.html), [much](https://kotlinlang.org/docs/reference/lambdas.html) nicer than java.

Straight to the point: would you accept a MR converting Red Moon to kotlin?

**Comment by smichel17** [comment]
Kotlin has really good [java interoperability](https://kotlinlang.org/docs/reference/java-interop.html), so it's possible to convert files one at a time (ie, any time you're going to make a change). The Android Studio kotlin plugin also has automatic kotlin -> java conversion which works, although it doesn't really give you the full benefit of switching since it's just straight syntax conversion.

**Comment by smichel17** [comment]
@raatmarien Or, just thoughts?

**Comment by smichel17** [comment]
@raatmarien If you're anything except strictly opposed to this, I'm going to go ahead and convert a file or two, to try to convince you of how nice this would be :P

**Comment by smichel17** [comment]
See #95

**Comment by smichel17** [comment]
@raatmarien Being impatient, I'm going to convert the whole thing and hope that you're on board with that, and if it turns out otherwise, we'll cross that bridge when we get there.

**Comment by raatmarien** [comment]
Sorry for never replying in this issue, I think that this can be closed now since #95 is merged :smile:
