### ISSUE TITLE
Typo in app description on Google Play.

### ISSUE THREAD

**Issue by Kasijjuf** [raatmarien/red-moon#96]
In the app description, the sentence:

Red Moon is licensed under the GNU General Public License or, at your option any later version.

should instead read

Red Moon is licensed under the GNU General Public License, either version 3 of the License, or (at your option) any later version.

**Comment by raatmarien** [comment]
Thanks! The fixed version should be online in a few hours :+1:

**Comment by Kasijjuf** [comment]
I'm still not seeing the updated text.

**Comment by raatmarien** [comment]
Hmm, weird, thanks for the reminder. It seems like the update didn't get through.

I've submitted it again and will check if it got through tomorrow.

**Comment by raatmarien** [comment]
The updated text is life now (at least for me).

**Comment by smichel17** [comment]
It is updated for me as well.

**Comment by Kasijjuf** [comment]
LGTM
